UPDATE report_records
SET status = 'OPEN'
WHERE status = 'PENDING';

ALTER TABLE report_records ADD COLUMN review_note VARCHAR(1000);
ALTER TABLE report_records ADD COLUMN resolution_type VARCHAR(60);
ALTER TABLE report_records ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE violation_records ADD COLUMN severity VARCHAR(30) DEFAULT 'LOW' NOT NULL;
ALTER TABLE violation_records ADD COLUMN penalty_type VARCHAR(40) DEFAULT 'CREDIT_ONLY' NOT NULL;
ALTER TABLE violation_records ADD COLUMN target_type VARCHAR(40);
ALTER TABLE violation_records ADD COLUMN target_id BIGINT;
ALTER TABLE violation_records ADD COLUMN admin_id BIGINT;
ALTER TABLE violation_records ADD COLUMN deposit_impact_note VARCHAR(500);

CREATE TABLE credit_adjustment_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    violation_id BIGINT,
    before_score INT NOT NULL,
    delta_score INT NOT NULL,
    after_score INT NOT NULL,
    reason VARCHAR(500) NOT NULL,
    admin_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE user_restrictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    violation_id BIGINT,
    restriction_type VARCHAR(40) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    starts_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ends_at TIMESTAMP,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    admin_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE admin_action_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT,
    action_type VARCHAR(80) NOT NULL,
    target_type VARCHAR(40) NOT NULL,
    target_id BIGINT NOT NULL,
    note VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
