ALTER TABLE service_fee_records
    ADD COLUMN payment_order_no VARCHAR(64),
    ADD COLUMN payment_provider VARCHAR(40),
    ADD COLUMN payment_center_order_no VARCHAR(80),
    ADD COLUMN pay_url VARCHAR(1000),
    ADD COLUMN expires_at TIMESTAMP,
    ADD COLUMN failed_at TIMESTAMP,
    ADD COLUMN failure_reason VARCHAR(500),
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

CREATE UNIQUE INDEX uk_service_fee_payment_order_no ON service_fee_records (payment_order_no);
CREATE INDEX idx_service_fee_payment_status_time ON service_fee_records (status, created_at);

CREATE TABLE payment_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    business_type VARCHAR(40) NOT NULL,
    business_id BIGINT NOT NULL,
    payer_id BIGINT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    provider_order_no VARCHAR(80),
    pay_url VARCHAR(1000),
    status VARCHAR(30) NOT NULL,
    expires_at TIMESTAMP,
    paid_at TIMESTAMP,
    failed_at TIMESTAMP,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_payment_order_no ON payment_orders (order_no);
CREATE INDEX idx_payment_order_business ON payment_orders (business_type, business_id);
CREATE INDEX idx_payment_order_provider_order ON payment_orders (provider_order_no);
CREATE INDEX idx_payment_order_status_time ON payment_orders (status, created_at);

CREATE TABLE payment_callback_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(100) NOT NULL,
    order_no VARCHAR(64) NOT NULL,
    provider_order_no VARCHAR(80),
    status VARCHAR(30) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    verified BOOLEAN NOT NULL,
    handled BOOLEAN NOT NULL,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_payment_callback_event_id ON payment_callback_events (event_id);
CREATE INDEX idx_payment_callback_order_time ON payment_callback_events (order_no, created_at);

ALTER TABLE role_applications
    ALTER COLUMN deposit_status SET DEFAULT 'PENDING';
ALTER TABLE role_applications
    ADD COLUMN deposit_payment_order_no VARCHAR(64);

CREATE UNIQUE INDEX uk_role_application_deposit_order ON role_applications (deposit_payment_order_no);
