ALTER TABLE wallet_flows
    ADD COLUMN flow_type VARCHAR(40) NOT NULL DEFAULT 'LEGACY',
    ADD COLUMN available_balance_after DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN frozen_balance_after DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN idempotency_key VARCHAR(100),
    ADD COLUMN counterparty_user_id BIGINT,
    ADD COLUMN created_by VARCHAR(40) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN operator_id BIGINT;

UPDATE wallet_flows
SET available_balance_after = balance_after,
    frozen_balance_after = 0.00,
    flow_type = 'LEGACY',
    created_by = 'SYSTEM'
WHERE flow_type = 'LEGACY';

CREATE UNIQUE INDEX uk_wallet_flows_idempotency_key ON wallet_flows (idempotency_key);
CREATE INDEX idx_wallet_flows_type_time ON wallet_flows (flow_type, created_at);
CREATE INDEX idx_wallet_flows_counterparty_time ON wallet_flows (counterparty_user_id, created_at);

CREATE TABLE wallet_recharge_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    channel VARCHAR(40) NOT NULL,
    channel_fee DECIMAL(10,2) DEFAULT 0.00 NOT NULL,
    net_amount DECIMAL(10,2) NOT NULL,
    payment_order_no VARCHAR(64),
    status VARCHAR(40) DEFAULT 'PENDING' NOT NULL,
    review_note VARCHAR(500),
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP,
    paid_at TIMESTAMP,
    failed_at TIMESTAMP,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_wallet_recharge_order_no ON wallet_recharge_orders (order_no);
CREATE INDEX idx_wallet_recharge_user_time ON wallet_recharge_orders (user_id, created_at);
CREATE INDEX idx_wallet_recharge_status_time ON wallet_recharge_orders (status, created_at);
CREATE INDEX idx_wallet_recharge_payment_order ON wallet_recharge_orders (payment_order_no);

CREATE TABLE wallet_withdrawal_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    channel VARCHAR(40) NOT NULL,
    account_snapshot VARCHAR(255) NOT NULL,
    status VARCHAR(40) DEFAULT 'PENDING_REVIEW' NOT NULL,
    review_note VARCHAR(500),
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP,
    completed_at TIMESTAMP,
    rejected_at TIMESTAMP,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_wallet_withdrawal_request_no ON wallet_withdrawal_requests (request_no);
CREATE INDEX idx_wallet_withdrawal_user_time ON wallet_withdrawal_requests (user_id, created_at);
CREATE INDEX idx_wallet_withdrawal_status_time ON wallet_withdrawal_requests (status, created_at);

CREATE TABLE wallet_frozen_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    freeze_no VARCHAR(64) NOT NULL,
    wallet_account_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    target_type VARCHAR(40) NOT NULL,
    target_id BIGINT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    status VARCHAR(40) DEFAULT 'FROZEN' NOT NULL,
    reason VARCHAR(500),
    frozen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    released_at TIMESTAMP,
    canceled_at TIMESTAMP,
    consumed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_wallet_frozen_freeze_no ON wallet_frozen_records (freeze_no);
CREATE INDEX idx_wallet_frozen_user_status ON wallet_frozen_records (user_id, status, created_at);
CREATE INDEX idx_wallet_frozen_target ON wallet_frozen_records (target_type, target_id);
CREATE INDEX idx_wallet_frozen_status_time ON wallet_frozen_records (status, created_at);

ALTER TABLE goods_orders
    ADD COLUMN trade_mode VARCHAR(40) NOT NULL DEFAULT 'OFFLINE',
    ADD COLUMN escrow_status VARCHAR(40) NOT NULL DEFAULT 'NONE',
    ADD COLUMN escrow_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN platform_service_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN escrow_frozen_at TIMESTAMP,
    ADD COLUMN escrow_released_at TIMESTAMP,
    ADD COLUMN escrow_canceled_at TIMESTAMP,
    ADD COLUMN escrow_disputed_at TIMESTAMP,
    ADD COLUMN escrow_cancel_reason VARCHAR(500),
    ADD COLUMN escrow_dispute_reason VARCHAR(500);

CREATE INDEX idx_goods_orders_trade_time ON goods_orders (trade_mode, created_at);
CREATE INDEX idx_goods_orders_escrow_status_time ON goods_orders (escrow_status, created_at);
CREATE INDEX idx_goods_orders_buyer_escrow ON goods_orders (buyer_id, escrow_status, created_at);
CREATE INDEX idx_goods_orders_seller_escrow ON goods_orders (seller_id, escrow_status, created_at);
