ALTER TABLE wallet_flows
    ADD COLUMN flow_type VARCHAR(40) NOT NULL DEFAULT 'LEGACY',
    ADD COLUMN available_balance_after DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN frozen_balance_after DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN idempotency_key VARCHAR(120),
    ADD COLUMN counterparty_user_id BIGINT,
    ADD COLUMN created_by VARCHAR(40) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN operator_id BIGINT;

UPDATE wallet_flows
SET available_balance_after = balance_after,
    frozen_balance_after = 0.00,
    flow_type = 'LEGACY',
    created_by = 'SYSTEM'
WHERE flow_type = 'LEGACY';

CREATE UNIQUE INDEX uk_wallet_flows_idempotency_key ON wallet_flows (idempotency_key);
CREATE INDEX idx_wallet_flows_type_time ON wallet_flows (flow_type, created_at);
CREATE INDEX idx_wallet_flows_business ON wallet_flows (business_type, business_id);
CREATE INDEX idx_wallet_flows_counterparty_time ON wallet_flows (counterparty_user_id, created_at);

CREATE TABLE wallet_recharge_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recharge_no VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    channel VARCHAR(30) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    channel_fee DECIMAL(10,2) DEFAULT 0.00 NOT NULL,
    pay_amount DECIMAL(10,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    payment_order_no VARCHAR(64),
    review_note VARCHAR(500),
    reviewer_id BIGINT,
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_wallet_recharge_no ON wallet_recharge_orders (recharge_no);
CREATE INDEX idx_wallet_recharge_user_time ON wallet_recharge_orders (user_id, created_at);
CREATE INDEX idx_wallet_recharge_status_time ON wallet_recharge_orders (status, created_at);
CREATE INDEX idx_wallet_recharge_payment_order ON wallet_recharge_orders (payment_order_no);

CREATE TABLE wallet_withdrawal_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    withdrawal_no VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    channel VARCHAR(30) NOT NULL,
    account_snapshot VARCHAR(200),
    status VARCHAR(30) NOT NULL,
    review_note VARCHAR(500),
    reviewer_id BIGINT,
    reviewed_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_wallet_withdrawal_no ON wallet_withdrawal_requests (withdrawal_no);
CREATE INDEX idx_wallet_withdrawal_user_time ON wallet_withdrawal_requests (user_id, created_at);
CREATE INDEX idx_wallet_withdrawal_status_time ON wallet_withdrawal_requests (status, created_at);

CREATE TABLE wallet_frozen_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    freeze_no VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    business_type VARCHAR(40) NOT NULL,
    business_id BIGINT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    frozen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    released_at TIMESTAMP,
    remark VARCHAR(500)
);

CREATE UNIQUE INDEX uk_wallet_freeze_no ON wallet_frozen_records (freeze_no);
CREATE INDEX idx_wallet_freeze_user_status ON wallet_frozen_records (user_id, status);
CREATE INDEX idx_wallet_freeze_business ON wallet_frozen_records (business_type, business_id);

ALTER TABLE goods_orders
    ADD COLUMN trade_mode VARCHAR(40) NOT NULL DEFAULT 'OFFLINE',
    ADD COLUMN escrow_status VARCHAR(40) NOT NULL DEFAULT 'NONE',
    ADD COLUMN escrow_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN platform_service_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN escrow_frozen_at TIMESTAMP,
    ADD COLUMN escrow_released_at TIMESTAMP,
    ADD COLUMN escrow_unfrozen_at TIMESTAMP,
    ADD COLUMN cancel_reason VARCHAR(500),
    ADD COLUMN dispute_reason VARCHAR(500);

CREATE INDEX idx_goods_orders_trade_time ON goods_orders (trade_mode, created_at);
CREATE INDEX idx_goods_orders_escrow_status_time ON goods_orders (escrow_status, created_at);
CREATE INDEX idx_goods_orders_buyer_escrow ON goods_orders (buyer_id, escrow_status, created_at);
CREATE INDEX idx_goods_orders_seller_escrow ON goods_orders (seller_id, escrow_status, created_at);
