ALTER TABLE goods ADD COLUMN campus_zone VARCHAR(40) NOT NULL DEFAULT 'OTHER';
ALTER TABLE goods ADD COLUMN contact_visibility VARCHAR(40) NOT NULL DEFAULT 'INTENT_ONLY';
ALTER TABLE goods ADD COLUMN delivery_method VARCHAR(40) NOT NULL DEFAULT 'OFFLINE_MEETUP';
ALTER TABLE goods ADD COLUMN service_fee_policy VARCHAR(40) NOT NULL DEFAULT 'NONE';
ALTER TABLE goods ADD COLUMN published_at TIMESTAMP NULL;
ALTER TABLE goods ADD COLUMN sold_at TIMESTAMP NULL;
ALTER TABLE goods ADD COLUMN sold_to_user_id BIGINT NULL;
ALTER TABLE goods ADD CONSTRAINT fk_goods_sold_to_user FOREIGN KEY (sold_to_user_id) REFERENCES users(id);

CREATE TABLE goods_intents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_id BIGINT NOT NULL,
    buyer_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    message VARCHAR(500) NULL,
    contact_snapshot VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL,
    service_fee_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_goods_intent_goods FOREIGN KEY (goods_id) REFERENCES goods(id),
    CONSTRAINT fk_goods_intent_buyer FOREIGN KEY (buyer_id) REFERENCES users(id),
    CONSTRAINT fk_goods_intent_seller FOREIGN KEY (seller_id) REFERENCES users(id),
    CONSTRAINT fk_goods_intent_fee FOREIGN KEY (service_fee_id) REFERENCES service_fee_records(id),
    CONSTRAINT uk_goods_intent_buyer_goods UNIQUE (goods_id, buyer_id)
);
CREATE INDEX idx_goods_status_zone_time ON goods (status, campus_zone, created_at);
CREATE INDEX idx_goods_intent_seller_status ON goods_intents (seller_id, status);
CREATE INDEX idx_goods_intent_buyer_time ON goods_intents (buyer_id, created_at);
CREATE INDEX idx_reviews_target_user_time ON reviews (target_user_id, created_at);
